name: Woking Dirs & Shell 
on: [push]
defaults:
  run: 
    shell: bash
jobs:
  display-wd-info:
     runs-on: ubuntu-latest
     steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a 
  display-wd-info-windows:
      runs-on: windows-latest
      steps:
        - name: Display Working Directory & List Files
          run: |
            Get-Location
            dir 
        - name: Python Shell
          shell: Python
          run: |
            import platform
            print(platform.processor())
